[package]
name = "msf-client"
version = "0.1.0"
authors = ["Hristo Asenov <hristo.s.asenov@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.90", features = ["derive"]}
rmp-serde = "0.13.7"
reqwest = "0.9.15"
